/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of a network block check */
export interface BlockResult {
  blocked: boolean
  redirect?: string
  exception?: string
}
/** Result of a cosmetic filter check */
export interface CosmeticResult {
  hideSelectors: Array<string>
  styleSelectors: Array<string>
  injectedScript: string
}
/**
 * Brave-grade ad & tracker blocking engine.
 * Uses Brave's adblock-rust crate for full EasyList/uBlock Origin filter support,
 * cosmetic filtering, and $exception / $redirect rules.
 */
export declare class ShieldEngine {
  /** Create a new ShieldEngine with embedded fallback filters. */
  constructor()
  /**
   * Load filter lists (EasyList, uBlock, etc.) from raw text.
   * Each entry in `filter_texts` is the raw content of a filter list file.
   * Returns the total number of filters loaded.
   */
  loadFilterLists(filterTexts: Array<string>): number
  /**
   * Check if a URL should be blocked.
   * `source_url` is the page that initiated the request.
   * `request_type` is the resource type: "script", "image", "stylesheet", "xmlhttprequest", etc.
   */
  checkNetworkRequest(url: string, sourceUrl: string, requestType: string): BlockResult
  /**
   * Legacy compatibility: simple boolean check.
   * Wraps check_network_request for backward compatibility.
   */
  shouldBlock(rawUrl: string): boolean
  /**
   * Get cosmetic filters for a specific URL.
   * Returns CSS selectors to hide and style rules to inject.
   */
  getCosmeticFilters(url: string): CosmeticResult
  /** Return the number of filters loaded. */
  filterCount(): number
  /** Legacy alias for filter_count. */
  domainCount(): number
  /** Serialize the engine to a byte buffer for caching. */
  serialize(): Array<number>
  /**
   * Deserialize the engine from a cached byte buffer.
   * Returns true if successful.
   */
  deserialize(data: Array<number>): boolean
}
