/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * High-performance ad & tracker blocking engine.
 * Stores blocked domains in a HashSet for O(1) lookup.
 * Checks the hostname and all parent domains (e.g. ads.example.com -> example.com).
 */
export declare class ShieldEngine {
  /** Create a new ShieldEngine pre-loaded with known ad/tracker domains. */
  constructor()
  /**
   * Check if a URL should be blocked.
   * Parses the URL, extracts the hostname, and walks up the domain hierarchy.
   * Returns true if any level matches a blocked domain.
   */
  shouldBlock(rawUrl: string): boolean
  /** Return the number of domains in the blocked set. */
  domainCount(): number
  /** Add a custom domain to the block list at runtime. */
  addDomain(domain: string): void
  /** Remove a domain from the block list at runtime. */
  removeDomain(domain: string): boolean
}
